### ISSUE TITLE
Get APIs (and get them to work)

### ISSUE THREAD

**Issue by ctracey92** [ctracey92/project1#9]
# Find a new beer API that is open and free
## As a user we need to be able to access the APIs for our seachers
###Tasks
- [x] Find a new beer API
- [x] Start working on the AJAX requests for the two APIs (beer/food)
- [x] Format the results into a variable to be used

**Comment by ctracey92** [comment]
> # Find a new beer API that is open and free
> ## As a user we need to be able to access the APIs for our searchers
> ###Tasks
> 
> * [ ]  Find a new beer API
> * [ ] Start working on the AJAX requests for the two APIs (beer/food)
> * [ ]  Format the results into a variable to be used
